In [1]:
# Importing libraries

import numpy as np
#import matplotlib.pyplot as mtp
import pandas as pd

In [2]:
#importing datasets

data_set = pd .read_csv('Data.csv')

In [3]:
#Extracting independent variable

x = data_set.iloc[:,:-1].values

#Extracting dependent variable

y = data_set.iloc[:,3].values

In [4]:
#Handling missing data (Replacing missing data with the mean value)

from sklearn.impute import SimpleImputer

imputer = SimpleImputer(missing_values=np.nan,strategy='mean')

In [5]:
#Fitting imputer object to the independent variables x.
imputerimputer = imputer.fit(x[:,1:3])

#Replacing missing data with the calculated mean value 
x[:,1:3] = imputer.transform(x[:,1:3])

In [6]:
#Catgorical data
# for Country variable 

from sklearn.preprocessing import LabelEncoder, OneHotEncoder
from sklearn.compose import ColumnTransformer

lable_encoder_x = LabelEncoder()

x[:,0] = lable_encoder_x.fit_transform(x[:,0])

In [7]:
#Encoding for dummy variable

ct = ColumnTransformer(transformers=[("Country",OneHotEncoder(),[0])],remainder = 'passthrough')

x = np.array(ct.fit_transform(x),dtype = np.float)

In [8]:
#Encoding for purchased variable 

labelencoder_y = LabelEncoder()

y = labelencoder_y.fit_transform(y)

In [9]:
#Splitting the dataset into training and test set

from sklearn.model_selection import train_test_split

x_train,x_test,y_train,y_test = train_test_split(x,y,test_size=0.2,random_state=0)

In [11]:
#Feature Scaling of datasets

from sklearn.preprocessing import StandardScaler

st_x = StandardScaler()

x_train = st_x.fit_transform(x_train)

x_test = st_x.transform(x_test)


In [12]:
print(x_test)

[[-1.          1.73205081 -0.57735027 -2.41578041 -0.90681902]
 [-1.         -0.57735027  1.73205081  1.82656568  2.24643804]]


In [13]:
print(x_train)
print(y_test)
print(y_train)

[[-1.          1.73205081 -0.57735027 -0.29460737  0.1339619 ]
 [ 1.         -0.57735027 -0.57735027 -0.93095928  1.22626663]
 [ 1.         -0.57735027 -0.57735027  0.34174455 -1.74150472]
 [-1.          1.73205081 -0.57735027 -0.05892147 -0.99956188]
 [ 1.         -0.57735027 -0.57735027  1.61444837  1.41175234]
 [ 1.         -0.57735027 -0.57735027  1.40233107  0.11335238]
 [-1.         -0.57735027  1.73205081 -0.71884198  0.39158094]
 [-1.         -0.57735027  1.73205081 -1.35519389 -0.5358476 ]]
[0 0]
[1 1 1 0 1 0 0 1]


In [14]:
print(data_set)

   Country   Age   Salary Purchased
0    India  38.0  68000.0        No
1   France  43.0  45000.0       Yes
2  Germany  30.0  54000.0        No
3   France  48.0  65000.0        No
4  Germany  40.0      NaN       Yes
5    India  35.0  58000.0       Yes
6  Germany   NaN  53000.0        No
7   France  49.0  79000.0       Yes
8    India  50.0  88000.0        No
9   France  37.0  77000.0       Yes


In [15]:
print(x)
print(y)

[[0.00000000e+00 0.00000000e+00 1.00000000e+00 3.80000000e+01
  6.80000000e+04]
 [1.00000000e+00 0.00000000e+00 0.00000000e+00 4.30000000e+01
  4.50000000e+04]
 [0.00000000e+00 1.00000000e+00 0.00000000e+00 3.00000000e+01
  5.40000000e+04]
 [1.00000000e+00 0.00000000e+00 0.00000000e+00 4.80000000e+01
  6.50000000e+04]
 [0.00000000e+00 1.00000000e+00 0.00000000e+00 4.00000000e+01
  6.52222222e+04]
 [0.00000000e+00 0.00000000e+00 1.00000000e+00 3.50000000e+01
  5.80000000e+04]
 [0.00000000e+00 1.00000000e+00 0.00000000e+00 4.11111111e+01
  5.30000000e+04]
 [1.00000000e+00 0.00000000e+00 0.00000000e+00 4.90000000e+01
  7.90000000e+04]
 [0.00000000e+00 0.00000000e+00 1.00000000e+00 5.00000000e+01
  8.80000000e+04]
 [1.00000000e+00 0.00000000e+00 0.00000000e+00 3.70000000e+01
  7.70000000e+04]]
[0 1 0 0 1 1 0 1 0 1]
